package APCD;

import business.UserBusiness;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import utils.Util;
import xml.Users;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class TableOfMeasurements extends javax.swing.JFrame {

    /**
     * Creates new form TableOfMeasurements
     */
    private static TableOfMeasurements instance;

    private TableOfMeasurements() {
        initComponents();
        initForm();

    }

    public static TableOfMeasurements getInstance() {
        if (instance == null) {
            instance = new TableOfMeasurements();
        }

        instance.loadData();
        instance.initializeDataTable();
        return instance;

    }

    private void initForm() {
        Util.initializeForm(this);
        loadData();
        initializeDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ExitMeasurTabel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        measrementTable = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        sendMail = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Measurement view");
        setPreferredSize(new java.awt.Dimension(1050, 432));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infoPic.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ExitMeasurTabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        ExitMeasurTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        ExitMeasurTabel.setToolTipText("Back");
        ExitMeasurTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMeasurTabelActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apc diabeticlogo DailyM.png"))); // NOI18N

        measrementTable.setAutoCreateRowSorter(true);
        measrementTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        measrementTable.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        measrementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        measrementTable.setToolTipText("Table of Measurments");
        measrementTable.setGridColor(new java.awt.Color(204, 255, 204));
        measrementTable.setRowHeight(26);
        measrementTable.setSelectionBackground(new java.awt.Color(255, 255, 204));
        measrementTable.setSelectionForeground(new java.awt.Color(153, 0, 0));
        jScrollPane1.setViewportView(measrementTable);

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 51, 255));
        nameLabel.setText("NAME");

        sendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mail-icon.png"))); // NOI18N
        sendMail.setToolTipText("Send to Email");
        sendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMailActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 51, 255));
        genderLabel.setText("v_Gender");

        nameLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(0, 153, 51));
        nameLabel1.setText("NAME   : ");

        nameLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(0, 153, 51));
        nameLabel2.setText("Type     :");

        nameLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(0, 153, 51));
        nameLabel3.setText("Gender :");

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(0, 51, 255));
        typeLabel.setText("v_type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel1)
                            .addComponent(nameLabel2)
                            .addComponent(nameLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(genderLabel)
                            .addComponent(typeLabel))
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendMail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(ExitMeasurTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1291, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(nameLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel2)
                            .addComponent(typeLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendMail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(ExitMeasurTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(334, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMeasurTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMeasurTabelActionPerformed
        DailyMeasurement dm = DailyMeasurement.getInstance();
        dm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ExitMeasurTabelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMailActionPerformed
        // TODO add your handling code here:
        Util.fireEmail(Util.currentLoginUser.getEmail(), userBusiness.prepareUserDetailsString());

    }//GEN-LAST:event_sendMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitMeasurTabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable measrementTable;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JButton sendMail;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    UserBusiness userBusiness = new UserBusiness();

    Map<Integer, Users.UserInfo.DailyMeasurement> extractLastSevenDailyMeasurements;

    private void loadData() {

        extractLastSevenDailyMeasurements = userBusiness.extractLastSevenDailyMeasurements();
        
        nameLabel.setText((Util.currentLoginUser.getName() != null) ? Util.currentLoginUser.getName() : "");
        genderLabel.setText((Util.currentLoginUser.getGender() != null) ? Util.currentLoginUser.getGender() : "");
        typeLabel.setText((Util.currentLoginUser.getTypeOfDiabetic() != null) ? Util.currentLoginUser.getTypeOfDiabetic() : "");

    }

    private void initializeDataTable() {
        if(extractLastSevenDailyMeasurements!=null){
            
            List<String> columns = new ArrayList();
        
            for(String time : Util.times){
                columns.add(Util.camelCasingStylingToNormal(time));
            }
            List<String[]> values = new ArrayList<String[]>();

            for (int day : extractLastSevenDailyMeasurements.keySet()) {
                Users.UserInfo.DailyMeasurement data = extractLastSevenDailyMeasurements.get(day);
                List<String> rowData = new ArrayList();

                rowData.add(String.format("%s %s", Util.refineWidth(Util.toDateString(data.getMeasurementDate()), 11), Util.weekDays[day]));
                if (data == null) {
                    data = new Users.UserInfo.DailyMeasurement();
                rowData.addAll(Arrays.asList(data.getDataAsStringArray()));
                values.add(rowData.toArray(new String[rowData.size()]));
                Collections.sort(rowData);
            }
            TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][]{}), columns.toArray());
            measrementTable.setModel(tableModel);
            System.out.println();
            }
        }
    }
}
