package APCD;

import business.UserBusiness;
import java.awt.Component;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SwingUtilities;
import javax.xml.datatype.XMLGregorianCalendar;
import util.Utils;
import xml.ObjectFactory;
import xml.Users;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Toshiba
 */
public class TimeSetting extends javax.swing.JFrame {

    /**
     * Creates new form TimeSetting
     */
    UserBusiness userBusiness = new UserBusiness();
    private static TimeSetting instance;
    private TimeSetting() {
        initComponents();
        initForm();
        loadData();
    }

    private void initForm() {
        Utils.initializeForm(this);
        FlowLayout layout = new FlowLayout();
        beforeBreakFastPanel.setLayout(layout);
        breakfastpanel.setLayout(layout);
        lunchPanel.setLayout(layout);
        dinnerPanel.setLayout(layout);
        beforeSleepPanel.setLayout(layout);
    }

    public static TimeSetting getInstance()
    {
        if(instance ==null)
        {
        instance = new TimeSetting();
        }
        return instance;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        DayLabel = new javax.swing.JLabel();
        cancelTime = new javax.swing.JButton();
        saveTime = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        timePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        beforeBreakFastPanel = new javax.swing.JPanel();
        breakfastpanel = new javax.swing.JPanel();
        lunchPanel = new javax.swing.JPanel();
        dinnerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        beforeSleepPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Setting");

        DayLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        DayLabel.setText("Day :");

        cancelTime.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cancelTime.setText("Cancel");
        cancelTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTimeActionPerformed(evt);
            }
        });

        saveTime.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        saveTime.setText("Save");
        saveTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTimeActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apc diabetic2.png"))); // NOI18N

        timePanel.setBackground(new java.awt.Color(255, 255, 204));
        timePanel.setForeground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Before Sleep");

        jLabel3.setText("Before Breakfast");

        jLabel4.setText("Breakfast");

        jLabel5.setText("Lunch");

        beforeBreakFastPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout beforeBreakFastPanelLayout = new javax.swing.GroupLayout(beforeBreakFastPanel);
        beforeBreakFastPanel.setLayout(beforeBreakFastPanelLayout);
        beforeBreakFastPanelLayout.setHorizontalGroup(
            beforeBreakFastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        beforeBreakFastPanelLayout.setVerticalGroup(
            beforeBreakFastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout breakfastpanelLayout = new javax.swing.GroupLayout(breakfastpanel);
        breakfastpanel.setLayout(breakfastpanelLayout);
        breakfastpanelLayout.setHorizontalGroup(
            breakfastpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        breakfastpanelLayout.setVerticalGroup(
            breakfastpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lunchPanelLayout = new javax.swing.GroupLayout(lunchPanel);
        lunchPanel.setLayout(lunchPanelLayout);
        lunchPanelLayout.setHorizontalGroup(
            lunchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        lunchPanelLayout.setVerticalGroup(
            lunchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dinnerPanelLayout = new javax.swing.GroupLayout(dinnerPanel);
        dinnerPanel.setLayout(dinnerPanelLayout);
        dinnerPanelLayout.setHorizontalGroup(
            dinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        dinnerPanelLayout.setVerticalGroup(
            dinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setText("dinner");

        javax.swing.GroupLayout beforeSleepPanelLayout = new javax.swing.GroupLayout(beforeSleepPanel);
        beforeSleepPanel.setLayout(beforeSleepPanelLayout);
        beforeSleepPanelLayout.setHorizontalGroup(
            beforeSleepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        beforeSleepPanelLayout.setVerticalGroup(
            beforeSleepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beforeSleepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(timePanelLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dinnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(timePanelLayout.createSequentialGroup()
                            .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(beforeBreakFastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(breakfastpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lunchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beforeBreakFastPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(breakfastpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lunchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(dinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(beforeSleepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveTime, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DayLabel)
                        .addGap(34, 34, 34)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelTime)
                            .addComponent(saveTime)))
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTimeActionPerformed
        DailyMeasurement dm =  DailyMeasurement.getInstance();
        dm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelTimeActionPerformed

    private void saveTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTimeActionPerformed

        if (userTimeSettings != null) 
        {
            if (userChangedAnyValue()) {
                boolean result = Utils.displayDialogMessage(this, "you have changed some value(s) do you want to save ?");
                {
                    if (result) {
                        updateCurrentData();
                        showDailyMeasurementForm();
                    } else {
                        showDailyMeasurementForm();
                    }
                }
            } else {
               
                showDailyMeasurementForm();
            }

        } else {
            constructUserTimeSetting();
            setUserSettingsData();
                saveNewData();
            showDailyMeasurementForm();

        }


    }//GEN-LAST:event_saveTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DayLabel;
    private javax.swing.JPanel beforeBreakFastPanel;
    private javax.swing.JPanel beforeSleepPanel;
    private javax.swing.JPanel breakfastpanel;
    private javax.swing.JButton cancelTime;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel dinnerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel lunchPanel;
    private javax.swing.JButton saveTime;
    private javax.swing.JPanel timePanel;
    // End of variables declaration//GEN-END:variables
    Date currentSelectedDate = currentSelectedDate = new Date();
    Users.UserInfo.UserTimeSetting userTimeSettings = null;

    private void loadData() {
        userTimeSettings = userBusiness.extractToDayUserTimeSetting();
        if (userTimeSettings != null) {
            setFieldsValues(userTimeSettings);
        } else {
            initializeTimePanelWithCurrentTime();
        }
        setDateLabelWithCurrentDate();
    }

    private void setFieldsValues(Users.UserInfo.UserTimeSetting userTimeSettings) {
        Date date = new Date();

        if (userTimeSettings.getBeforeBreakfast() != null) {
            beforeBreakFastPanel.add(Utils.createDatePicker(userTimeSettings.getBeforeBreakfast()));
        } else {
            breakfastpanel.add(Utils.createDatePicker(date));
        }

        if (userTimeSettings.getBreackfast() != null) {
            breakfastpanel.add(Utils.createDatePicker(userTimeSettings.getBreackfast()));
        } else {
            breakfastpanel.add(Utils.createDatePicker(date));
        }
        if (userTimeSettings.getLunch() != null) {
            lunchPanel.add(Utils.createDatePicker(userTimeSettings.getLunch()));
        } else {
            lunchPanel.add(Utils.createDatePicker(date));
        }
        if (userTimeSettings.getDinner() != null) {
            dinnerPanel.add(Utils.createDatePicker(userTimeSettings.getDinner()));
        } else {
            dinnerPanel.add(Utils.createDatePicker(date));
        }
        if (userTimeSettings.getBeforeSleep() != null) {
            beforeSleepPanel.add(Utils.createDatePicker(userTimeSettings.getBeforeSleep()));
        } else {
            beforeSleepPanel.add(Utils.createDatePicker(date));
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    private void initializeTimePanelWithCurrentTime() {

        Date date = new Date();
        for (Component c : timePanel.getComponents()) {
            if (c instanceof JPanel) {
                ((JPanel) c).add(Utils.createDatePicker(date));
            }
        }
    }

    private void setDateLabelWithCurrentDate() {
        ((JTextField) dateChooser.getDateEditor().getUiComponent()).setText("");
        dateChooser.setDate(new Date());
    }

    private Date getBeforeBreakFastDate() {
        return extractDateFromPanel(beforeBreakFastPanel);
    }

    private Date getBreakfast() {
        return extractDateFromPanel(breakfastpanel);
    }

    private Date getLunch() {
        return extractDateFromPanel(lunchPanel);
    }

    private Date getDinner() {
        return extractDateFromPanel(dinnerPanel);
    }

    private Date getBeforeSleep() {
        return extractDateFromPanel(beforeSleepPanel);
    }

    private Date extractDateFromPanel(JPanel panel) {

        for (Component c : panel.getComponents()) {
            if (c instanceof JSpinner) {
                JSpinner sp = (JSpinner) c;
                JComponent editor = sp.getEditor();
                if (editor instanceof JSpinner.DateEditor) {
                    String dateAsText = ((JSpinner.DateEditor) editor).getTextField().getText();
                    SimpleDateFormat dateFormat = ((JSpinner.DateEditor) editor).getFormat();
                    return Utils.constructDateOfFormat(dateAsText, dateFormat);
                }
            }
        }
        return null;
    }

    private boolean userChangedAnyValue() {

        if (!Utils.areTimesEqualsEachOthers(userTimeSettings.getBeforeBreakfast(), getBeforeBreakFastDate())) {
            return true;
        }
        if (!Utils.areTimesEqualsEachOthers(userTimeSettings.getBreackfast(), getBreakfast())) {
            return true;
        }
        if (!Utils.areTimesEqualsEachOthers(userTimeSettings.getLunch(), getLunch())) {
            return true;
        }
        if (!Utils.areTimesEqualsEachOthers(userTimeSettings.getDinner(), getDinner())) {
            return true;
        }
        if(!Utils.areTimesEqualsEachOthers(userTimeSettings.getBeforeSleep(), getBeforeSleep()))
        {
            return true;
        }
        return false;

    }

    private void showDailyMeasurementForm() {

        Utils.hideAndShow(this,  DailyMeasurement.getInstance());
    }

    private void constructUserTimeSetting() {
        userTimeSettings = new ObjectFactory().createUsersUserInfoUserTimeSetting();
        

    }

    private void saveNewData() {
        
        Utils.currentLoginUser.getUserTimeSetting().add(userTimeSettings);
        userBusiness.saveUsersBackIntoFile();
    
    }

    private void updateCurrentData() {
        setUserSettingsData();
                userBusiness.saveUsersBackIntoFile();

    }
    
    public void setUserSettingsData()
    {
        userTimeSettings.setUserTimeSettingDate(Utils.dateToXMLGregorianCalendar(new Date()));
        userTimeSettings.setBeforeBreakfast(Utils.dateToXMLGregorianCalendar(getBeforeBreakFastDate()));
        userTimeSettings.setBreackfast(Utils.dateToXMLGregorianCalendar(getBreakfast()));
        userTimeSettings.setLunch(Utils.dateToXMLGregorianCalendar(getLunch()));
        userTimeSettings.setDinner(Utils.dateToXMLGregorianCalendar(getDinner()));
        userTimeSettings.setBeforeSleep(Utils.dateToXMLGregorianCalendar(getBeforeSleep()));
    }
}
