//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:23:05 AM EET 
//


package xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link Users.UserInfo }
     * 
     */
    public Users.UserInfo createUsersUserInfo() {
        return new Users.UserInfo();
    }

    /**
     * Create an instance of {@link Users.UserInfo.DailyMeasurement }
     * 
     */
    public Users.UserInfo.DailyMeasurement createUsersUserInfoDailyMeasurement() {
        return new Users.UserInfo.DailyMeasurement();
    }

    /**
     * Create an instance of {@link Users.UserInfo.UserTimeSetting }
     * 
     */
    public Users.UserInfo.UserTimeSetting createUsersUserInfoUserTimeSetting() {
        return new Users.UserInfo.UserTimeSetting();
    }

    /**
     * Create an instance of {@link Users.UserInfo.DailyMeasurement.Measurement }
     * 
     */
    public Users.UserInfo.DailyMeasurement.Measurement createUsersUserInfoDailyMeasurementMeasurement() {
        return new Users.UserInfo.DailyMeasurement.Measurement();
    }

}
