//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:23:05 AM EET 
//
package xml;

import APCD.TimeSetting;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import utils.Util;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="typeOfDiabetic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="userTimeSetting" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="beforeBreakfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="breackfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="lunch" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="dinner" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="beforeSleep" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="userTimeSettingDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="dailyMeasurement" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="measurement" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="timeOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="measurementValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="measurementDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userInfo"
})
@XmlRootElement(name = "users")
public class Users {

    protected List<Users.UserInfo> userInfo;

    /**
     * Gets the value of the userInfo property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the userInfo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserInfo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Users.UserInfo }
     *
     *
     */
    public List<Users.UserInfo> getUserInfo() {
        if (userInfo == null) {
            userInfo = new ArrayList<Users.UserInfo>();
        }
        return this.userInfo;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="typeOfDiabetic" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="userTimeSetting" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="beforeBreakfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="breackfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="lunch" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="dinner" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="beforeSleep" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="userTimeSettingDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="dailyMeasurement" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="measurement" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="timeOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="measurementValue" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="measurementDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "gender",
        "typeOfDiabetic",
        "email",
        "userTimeSetting",
        "dailyMeasurement"
    })
    public static class UserInfo implements Cloneable {

        @XmlElement()
        protected String name;
        @XmlElement()
        protected String gender;
        @XmlElement()
        protected String typeOfDiabetic;
        @XmlElement()
        protected String email;
        protected List<Users.UserInfo.UserTimeSetting> userTimeSetting;
        protected List<Users.UserInfo.DailyMeasurement> dailyMeasurement;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the gender property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the typeOfDiabetic property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTypeOfDiabetic() {
            return typeOfDiabetic;
        }

        /**
         * Sets the value of the typeOfDiabetic property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTypeOfDiabetic(String value) {
            this.typeOfDiabetic = value;
        }

        /**
         * Gets the value of the email property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the userTimeSetting property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the userTimeSetting property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserTimeSetting().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Users.UserInfo.UserTimeSetting }
         *
         *
         */
        public List<Users.UserInfo.UserTimeSetting> getUserTimeSetting() {
            if (userTimeSetting == null) {
                userTimeSetting = new ArrayList<Users.UserInfo.UserTimeSetting>();
            }
            return this.userTimeSetting;
        }

        /**
         * Gets the value of the dailyMeasurement property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the dailyMeasurement property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDailyMeasurement().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Users.UserInfo.DailyMeasurement }
         *
         *
         */
        public void setDailyMeasurement(List<Users.UserInfo.DailyMeasurement> dailyMeasurement) {
            this.dailyMeasurement = dailyMeasurement;
        }

        public List<Users.UserInfo.DailyMeasurement> getDailyMeasurement() {
            if (dailyMeasurement == null) {
                dailyMeasurement = new ArrayList<Users.UserInfo.DailyMeasurement>();
            }
            return this.dailyMeasurement;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            } else if (obj instanceof Users.UserInfo) {
                if (((Users.UserInfo) obj).email != null) {
                    return ((Users.UserInfo) obj).email.equalsIgnoreCase(email);
                }
            }

            return false;

        }

        public Object clone() {
            List<DailyMeasurement> tempDailyMeasurements = new ArrayList();
            for (DailyMeasurement dailyMeasurement : getDailyMeasurement()) {
                tempDailyMeasurements.add((DailyMeasurement) dailyMeasurement.clone());
            }
            UserInfo userInfo = new UserInfo();
            userInfo.setDailyMeasurement(tempDailyMeasurements);
            return userInfo;

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="measurement" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="timeOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="measurementValue" type="{http://www.w3.org/2001/XMLSchema}float" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="measurementDate" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "measurement"
        })
        public static class DailyMeasurement implements Cloneable {

            protected List<Users.UserInfo.DailyMeasurement.Measurement> measurement;
            @XmlAttribute(name = "measurementDate")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar measurementDate;

            public static boolean doesMeasurementsInclude(List<Measurement> measurements, String measurementTime) {
                for (Measurement m : measurements) {
                    if (m.getTimeOfMeasurement() != null) {
                        if (m.getTimeOfMeasurement().equalsIgnoreCase(measurementTime)) {
                            return true;
                        }
                    }

                }
                return false;

            }

            public DailyMeasurement(String string) {

            }

            public DailyMeasurement() {

            }

            public static DailyMeasurement constructDefaultDailyMeasurement(int i) {

                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_MONTH, -(7 - i));
                DailyMeasurement dailyMeasurement = new DailyMeasurement();
                dailyMeasurement.setMeasurementDate(Util.dateToXMLGregorianCalendar(c.getTime()));

                for (int x = 0; x < 7; x++) {
                    dailyMeasurement.getMeasurement().add(new Measurement(Util.times[x], null));
                }
                return dailyMeasurement;
            }

            /**
             * Gets the value of the measurement property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the measurement property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMeasurement().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Users.UserInfo.DailyMeasurement.Measurement }
             *
             *
             */
            public List<Users.UserInfo.DailyMeasurement.Measurement> getMeasurement() {
                if (measurement == null) {
                    measurement = new ArrayList<Users.UserInfo.DailyMeasurement.Measurement>();
                }
                return this.measurement;
            }

            /**
             * Gets the value of the measurementDate property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getMeasurementDate() {
                return measurementDate;
            }

            /**
             * Sets the value of the measurementDate property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setMeasurementDate(XMLGregorianCalendar value) {
                this.measurementDate = value;
            }

            public boolean equals(Object obj) {

                if (obj == null) {
                    return false;
                }
                if (obj instanceof DailyMeasurement) {
                    DailyMeasurement tempDailyMeasurement = (DailyMeasurement) obj;

                    XMLGregorianCalendar measurementDate1 = tempDailyMeasurement.getMeasurementDate();
                    if (measurementDate1 != null && measurementDate != null) {

                        return ((measurementDate.getDay() == measurementDate1.getDay()) && (measurementDate.getMonth() == measurementDate1.getMonth()) && (measurementDate.getYear() == measurementDate1.getYear()));
                    }

                }
                return false;
            }

            @Override
            public Object clone() {
                DailyMeasurement dailyMeasurement = new DailyMeasurement();
                dailyMeasurement.setMeasurementDate(measurementDate);

                for (Measurement currentMeasurement : this.measurement) {
                    dailyMeasurement.getMeasurement().add(new Measurement(currentMeasurement.getTimeOfMeasurement(), currentMeasurement.getMeasurementValue()));

                }
                return dailyMeasurement;
            }

            public String[] getDataAsStringArray() {
                String[] result = new String[Util.times.length];
                for (int i = 0; i < result.length; i++) {

                    try {
                        result[i] = (measurement.get(i).getMeasurementValue() != null) ? measurement.get(i).getMeasurementValue() + "" : "";
                    } catch (Exception ex) {
                        result[i] = "";
                    }

                }
                return result;
            }

            public String toString() {
                StringBuilder stringBuilder = new StringBuilder();

                String str="                    ";
                for (int i = 0; i <Util.times.length; i++) {
                    
                    if(i==0)
                    {
                       
                    }
                    try {
                        str = (measurement.get(i).getMeasurementValue() != null) ? measurement.get(i).getMeasurementValue() + "" : "";
                    } catch (Exception ex) {
                        str = "";
                    }
                    str = Util.refineWidth(str);
                    stringBuilder.append(String.format("%s\t", str));
                }
                return stringBuilder.toString()+"\n";

            }
            
            
            
            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="timeOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="measurementValue" type="{http://www.w3.org/2001/XMLSchema}float" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Measurement {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "timeOfMeasurement")
                protected String timeOfMeasurement;
                @XmlAttribute(name = "measurementValue")
                protected Double measurementValue;

                public Measurement() {
                }

                public Measurement(String timeOfMeasurement, Double measurementValue) {
                    this.timeOfMeasurement = timeOfMeasurement;
                    this.measurementValue = measurementValue;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the timeOfMeasurement property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getTimeOfMeasurement() {
                    return timeOfMeasurement;
                }

                /**
                 * Sets the value of the timeOfMeasurement property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setTimeOfMeasurement(String value) {
                    this.timeOfMeasurement = value;
                }

                /**
                 * Gets the value of the measurementValue property.
                 *
                 * @return possible object is {@link Float }
                 *
                 */
                public Double getMeasurementValue() {
                    return measurementValue;
                }

                /**
                 * Sets the value of the measurementValue property.
                 *
                 * @param value allowed object is {@link Float }
                 *
                 */
                public void setMeasurementValue(Double value) {
                    this.measurementValue = value;
                }

                @Override
                public boolean equals(Object object) {
                    if (object != null && (object instanceof Measurement || object instanceof String)) {
                        if (object instanceof String) {
                            return ((String) object).equalsIgnoreCase(timeOfMeasurement);
                        } else {
                            return ((Measurement) object).timeOfMeasurement.equals(timeOfMeasurement);
                        }
                    }
                    return false;
                }

            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="beforeBreakfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="breackfast" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="lunch" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="dinner" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="beforeSleep" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *       &lt;/sequence>
         *       &lt;attribute name="userTimeSettingDate" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "beforeBreakfast",
            "breackfast",
            "lunch",
            "dinner",
            "beforeSleep"
        })
        public static class UserTimeSetting {

            @XmlElement()
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar beforeBreakfast;
            @XmlElement()
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar breackfast;
            @XmlElement()
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar lunch;
            @XmlElement()
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar dinner;
            @XmlElement()
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar beforeSleep;
            @XmlAttribute(name = "userTimeSettingDate")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar userTimeSettingDate;

            /**
             * Gets the value of the beforeBreakfast property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getBeforeBreakfast() {
                return beforeBreakfast;
            }

            /**
             * Sets the value of the beforeBreakfast property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setBeforeBreakfast(XMLGregorianCalendar value) {
                this.beforeBreakfast = value;
            }

            /**
             * Gets the value of the breackfast property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getBreackfast() {
                return breackfast;
            }

            /**
             * Sets the value of the breackfast property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setBreackfast(XMLGregorianCalendar value) {
                this.breackfast = value;
            }

            /**
             * Gets the value of the lunch property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getLunch() {
                return lunch;
            }

            /**
             * Sets the value of the lunch property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setLunch(XMLGregorianCalendar value) {
                this.lunch = value;
            }

            /**
             * Gets the value of the dinner property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getDinner() {
                return dinner;
            }

            /**
             * Sets the value of the dinner property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setDinner(XMLGregorianCalendar value) {
                this.dinner = value;
            }

            /**
             * Gets the value of the beforeSleep property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getBeforeSleep() {
                return beforeSleep;
            }

            /**
             * Sets the value of the beforeSleep property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setBeforeSleep(XMLGregorianCalendar value) {
                this.beforeSleep = value;
            }

            /**
             * Gets the value of the userTimeSettingDate property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getUserTimeSettingDate() {
                return userTimeSettingDate;
            }

            /**
             * Sets the value of the userTimeSettingDate property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setUserTimeSettingDate(XMLGregorianCalendar value) {
                this.userTimeSettingDate = value;
            }

        }

    }
}
